spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: 
  secretKey: 
  bucketName: 

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies
